### ISSUE TITLE
Feature Request: Support for Multi-Artists

### ISSUE THREAD

**Issue by killerkeks2** [UnicornsOnLSD/finamp#189]
I organize my library with Multi-Artists separated by "; ", which works wonderfully with Jellyfin itself.
Gelli doesn't recognize those tracks properly - it's always just one artist and the others aren't shown.

As i think, more users might like this feature, i opened this Issue. Thanks for your amazing software!

**Comment by UnicornsOnLSD** [comment]
Could you send a screenshot of what you see in Jellyfin/Finamp?

**Comment by rom4nik** [comment]
I think I've fixed this in #116.

**Comment by killerkeks2** [comment]
I was using the last release apk from August 2021 (an updated apk release file would be amazing, i had kinda trouble building it myself...) - now after building the latest version it's still not the way i expect. 

Multi Artists work fine, but i also defined Multi Album-Artists, which are not properly shown. 

e.g: 
"AlbumArtist":"NutriaDance","AlbumArtists":[{"Name":"NutriaDance","Id":"a3be82ebeb3729e0b83f3a006e841b14"},{"Name":"Zamurah","Id":"0e4e3cf4

First Album Item "+180" should show NutriaDance; Zamurah, but only shows NutriaDance as Album-Artist.

(Offtopic: Why are my album-images not shown correctly?)

I'll redefine the title and try to reopen the Issue, if that works for me. Thanks for your help!

![Screenshot_20220224-015431_Finamp](https://user-images.githubusercontent.com/97703119/155436402-500ee8aa-98d3-4436-8e11-e29f5cdfb154.png)
h

**Comment by UnicornsOnLSD** [comment]
I'll look into how this has been implemented in a minute. Your images are like that because you've built a debug build, so the app may be much more sluggish than it should be. Once I've looked into it I'll build a release APK here, since I'm pretty sure the release config needs you to mess around with signing keys and stuff.

As for a new release, I just have to finish off image downloading and a few other small things and then I'll make a release. I wanted it done by November but the university workload kind of killed that.

**Comment by UnicornsOnLSD** [comment]
Ah, looks like #116 pulls from artists instead of album artists. I'll change that to use album artists instead (unless someone tells me that doing that doesn't make sense lol)

**Comment by killerkeks2** [comment]
I think, for me #116 does make sense - my album artists are != to my artists. 

Example:

I have an Album from a Producer P, released on Label L. so my album artist is P;L
in 99% the tracks are all from producer P, which is also part of Producer.
If the producer has a feature with another producer (FP), it's only part of the producer-tag, e.g. P;FP.

Thats the way i organize it, i think thats a reasonable way. so in general i think:
- add the join to albumScreen, so under under +180 (album title) there's "Zamurah;Nutria Dance"
- add the join to albumScreen when opening each album next to the "People" Icon, above the trackcount

From my flutter-noobish perspective it seems, that #116 did a good job, but missed the join for album-artist.
Besides that i haven't found an actual problem.

Thanks! I might consider having a look into flutter in general too now, seems like a cool modern Appframework!

**Comment by UnicornsOnLSD** [comment]
Just changed it to use albumArtists in the album-artists branch, [here's a release APK](https://github.com/UnicornsOnLSD/finamp/files/8145487/release.zip). If it looks right to you, I'll clean it up and add it to master, I've kind of hacked it together at the moment

**Comment by UnicornsOnLSD** [comment]
As for Flutter, it's pretty cool and it has been really nice to bring Finamp to both iOS and Android, the only problems I have with it are around file handling (Dart/Flutter can only access files with direct paths, which is really jank) and there are some tiny animation differences that you notice, like the inkwell effect filling out slowly instead of in ~1 second. Other than that, highly recommended :)

**Comment by killerkeks2** [comment]
Hey James, i just tried out your release, thank you for your work! It's just not, what i expected. I'll add two pictures to hopefully make it more clear. Besides those two screeshots the master Branch was just fine regarding regular Artists.

![Screenshot_20220226-130225_Finamp](https://user-images.githubusercontent.com/97703119/155842662-e8f99c5a-8c9a-4ab6-a399-cbd5e9246d20.png)
![Screenshot_20220226-130235_Finamp](https://user-images.githubusercontent.com/97703119/155842664-5ee7d688-d798-4fcc-812f-2186559197e6.png)

**Comment by UnicornsOnLSD** [comment]
So that APK I sent didn't change anything? By the way, you're still running your debug build, so unless you uninstalled my build, you may have not seen the changes :)

**Comment by killerkeks2** [comment]
Yes Yes, it changed something, but at the wrong location. It didn't change anything at those two spots. What i've seen, you added the album-artist to the Music Player Bar on the bottom, which might be handy in general, too, but wasn't my problem.

I think, my problem isn't just relevant to me, thats why i created this issue :)

(oh, and of course i checked your apk, but reinstalled the debug build to show you those screenshots)

**Comment by UnicornsOnLSD** [comment]
Oh I see, I reverted that commit and changed it to the new method in those locations. [Here's another APK](https://github.com/UnicornsOnLSD/finamp/files/8146816/flutter-apk.zip). Let me know if there are any other issues :)

(by the way it should go without saying that these APKs are pre-release and stuff may break if you upgrade to 0.6 from them if I ever actually get it out)

**Comment by killerkeks2** [comment]
Amazing, that the way i expected it! Thank you very much! 

i'll have a look on your changes, too - i tried it myself but always got an error i didn't have time to look at in detail. having exams myself currently :/
